[tool.poetry]
name = "unir_msc_ai"
version = "0.1.0"
description = "Repo for projects done in the MSc of AI"
authors = ["Sergio Gomez"]
readme = "README.md"

[tool.poetry.dependencies]
python = "^3.11"
pandas = "^2.0.3"
matplotlib = "^3.7.2"
numpy = "^2.0.0"
requests = "^2.31.0"
black = "^23.7.0"
flake8 = "^6.1.0"
mypy = "^1.5.1"
pytest = "^7.4.0"
scikit-learn = "^1.4.1.post1"
seaborn = "^0.12.2"
pyarrow = "^17.0.0"
spacy = "^3.8.2"
es_core_news_md = { url = "https://github.com/explosion/spacy-models/releases/download/es_core_news_md-3.8.0/es_core_news_md-3.8.0-py3-none-any.whl" }
simpleai = "^0.8.3"
flask = "^3.1.0"
pydot = "^3.0.3"
graphviz = "^0.20.3"
opencv-python = "^4.10.0.84"
hampel = "^1.0.2"
bokeh = "^3.6.2"

[tool.poetry.group.dev.dependencies]
ipykernel = "^6.29.5"

[build-system]
requires = ["poetry-core"]
build-backend = "poetry.core.masonry.api"
